### ISSUE TITLE
Add fancy Command-Line Menu to accept RFC number

### ISSUE THREAD

**Issue by anirudhRowjee** [acmpesuecc/py-getrfc#5]
use a library like `rich` to create a fancy menu to take in the RFC Number,

**Comment by AlphaDelta1803** [comment]
Can I work on this

**Comment by prishagoel** [comment]
hey, just a quick question, the rfc number is a positional arguement right now which is fixed. for doing this code, will I have to change the parameter to make it optional?

**Comment by anirudhRowjee** [comment]
Hey @prishagoel 
Sure, we can look at making the RFC number an optional argument.

**Comment by anirudhlakhotia** [comment]
I'd like to work on this

**Comment by AyushmaanKaushik** [comment]
You've been assigned
